# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

checkRule1 <- function(grid, i, j) {
    .Call('_TakuzuR_checkRule1', PACKAGE = 'TakuzuR', grid, i, j)
}

checkRule2 <- function(grid, i, j) {
    .Call('_TakuzuR_checkRule2', PACKAGE = 'TakuzuR', grid, i, j)
}

